# Generated by Django 5.0.1 on 2024-02-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='slug',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
