# Generated by Django 5.0.1 on 2024-02-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_livro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
