# Generated by Django 5.0.1 on 2024-02-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_autor_remove_livro_autor_remove_livro_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='genero',
            new_name='generos',
        ),
    ]
